// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3GoSzjgK2ZuGUS-cQMB3-HSfszrGr9Wk',
    appId: '1:211408327113:web:224972e4f703ac5fc45818',
    messagingSenderId: '211408327113',
    projectId: 'bond007-8424d',
    authDomain: 'bond007-8424d.firebaseapp.com',
    storageBucket: 'bond007-8424d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlkCNRBlAmkRwgnizCL0LXANBkq7sHeoc',
    appId: '1:211408327113:android:9935835d886d7d26c45818',
    messagingSenderId: '211408327113',
    projectId: 'bond007-8424d',
    storageBucket: 'bond007-8424d.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA3GoSzjgK2ZuGUS-cQMB3-HSfszrGr9Wk',
    appId: '1:211408327113:web:561b229bfb07fba7c45818',
    messagingSenderId: '211408327113',
    projectId: 'bond007-8424d',
    authDomain: 'bond007-8424d.firebaseapp.com',
    storageBucket: 'bond007-8424d.firebasestorage.app',
  );
}
